name: Test workflow

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: pnpm install 

           
            - name: Build
              run: pnpm run build

            # Run tests (adapt for your test runner)
            - name: Run Linting
              run: pnpm run lint:f 
              if: always() # Always run tests, even if previous steps fail
